export NORMAL=$(tput sgr0)
export BRIGHT=$(tput bold)
export RED=$(tput setaf 1)
export GREEN=$(tput setaf 2)
export YELLOW=$(tput setaf 3)
export BLUE=$(tput setaf 4)
export CYAN=$(tput setaf 6)
export WHITE=$(tput setaf 7)
