openapi: "3.0.0"
info:
  title: Demo API
  description: A Demo API
  version: 0.0.1

servers:
  - url: https://localhost:8080/api/1

tags:
  - name: demo
    description: Contains all the demo APIs

components:
  schemas:
    SomeEnum:
      type: string
      enum:
        - value1
        - another-value
        - best_value
        - thevalue

    RangedValueList:
      type: array
      items:
        $ref: "#/components/schemas/RangedValue"

    RangedValue:
      properties:
        value:
          type: integer
          minimum: 5
          maximum: 50

paths:
  /demo:
    get:
      tags:
        - demo
      description: "A demo API"
      operationId: "getDemo"
      parameters:
        - in: query
          name: type
          description: The type of Demo.
          schema:
            type: array
            items:
              $ref: "#/components/schemas/SomeEnum"
          required: true

        - in: query
          name: rangedValues
          description: The values within ranged.
          schema:
            $ref: "#/components/schemas/RangedValueList"
          required: false

      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: string
