[sinks.my_console_sink]
type = "console"
inputs = [ "my_transform" ]
target = "stdout"

  [sinks.my_console_sink.encoding]
  codec = "json"

[sinks.my_blackhole_sink]
type = "blackhole"
inputs = [ "my_transform" ]
